language: java
jdk:
  - oraclejdk11
before_install:
  - chmod +x consumer/gradlew
  - chmod +x provider-spring/gradlew
  - chmod +x consumer/gradle/wrapper/gradle-wrapper.jar
  - chmod +x provider-spring/gradle/wrapper/gradle-wrapper.jar
script:
  - cd consumer
  - ./gradlew test
  - cd ../provider-spring
  - ./gradlew test
