language: java
jdk:
  - oraclejdk11
before_install:
  - chmod +x consumer/gradlew
  - chmod +x provider/gradlew
  - chmod +x consumer/gradle/wrapper/gradle-wrapper.jar
  - chmod +x provider/gradle/wrapper/gradle-wrapper.jar
script:
  - cd consumer
  - ./gradlew clean build
  - cd ../provider-spring
  - ./gradlew clean build
